<?php

/**
 * Implements hook_form_alter().
 */
function form_alter_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == "bb_advert_node_form") {
    $form['actions']['submit'] = array(
      '#type' => 'submit',
      '#value' => "Сохранить",
      '#weight' => 1,
      '#submit' => array('form_alter_advert_node_form_submit'),
    );
  }
}

function form_alter_advert_node_form_submit($form, &$form_state) {
  node_form_submit($form, $form_state);
  $form_state['redirect'] = url('/list', array(
      'absolute' => TRUE
    )
  );
  $_GET['destination'] = $form_state['redirect'];
}
